# Generated by Django 2.1.5 on 2022-10-12 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alb_title', models.CharField(max_length=50)),
                ('alb_slug', models.CharField(max_length=50, unique=True)),
                ('alb_about', models.CharField(blank=True, max_length=1000)),
                ('alb_release_date', models.DateTimeField(blank=True)),
                ('alb_views', models.BigIntegerField(default=1)),
                ('alb_cover', models.FileField(upload_to=music.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])])),
            ],
            options={
                'ordering': ['alb_title'],
            },
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to=music.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])])),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_firstname', models.CharField(max_length=50)),
                ('art_lastname', models.CharField(max_length=50)),
                ('art_username', models.CharField(max_length=50, unique=True)),
                ('art_about', models.TextField(blank=True, max_length=1000)),
                ('art_prof_pic', models.FileField(upload_to=music.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])])),
            ],
            options={
                'ordering': ['art_username'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_full', models.TextField()),
                ('ly_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('song_slug', models.CharField(max_length=50, unique=True)),
                ('song_views', models.BigIntegerField(default=1)),
                ('song_yt_link', models.CharField(blank=True, max_length=50)),
                ('song_file', models.FileField(upload_to=music.models.music_directory_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'ogg', 'aac'])])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('song_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Category')),
            ],
            options={
                'ordering': ['song_title'],
            },
        ),
        migrations.AddField(
            model_name='lyrics',
            name='ly_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Gallery'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
