# Generated by Django 2.1.5 on 2022-10-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20221013_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, to='music.Category'),
        ),
    ]
