# Generated by Django 2.1.5 on 2022-10-19 05:17

import django.core.validators
from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_art_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_cover_pic',
            field=models.FileField(default='-', upload_to=music.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])]),
        ),
    ]
