# Generated by Django 2.1.5 on 2022-10-19 05:46

import django.core.validators
from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_category_cat_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='alb_meta_tags',
            field=models.TextField(blank=True, default='-', max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='song_meta_tags',
            field=models.TextField(blank=True, default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_cover_pic',
            field=models.FileField(upload_to=music.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])]),
        ),
    ]
