# Generated by Django 2.1.5 on 2022-10-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20221019_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='lyrics',
            options={'verbose_name_plural': 'Lyrics'},
        ),
        migrations.AlterField(
            model_name='album',
            name='alb_slug',
            field=models.CharField(max_length=50),
        ),
    ]
