# Generated by Django 2.1.5 on 2022-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_artist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
