# Generated by Django 2.1.5 on 2022-10-22 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0013_song_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField()),
                ('liked_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
