# Generated by Django 2.1.5 on 2022-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_albumcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomments',
            name='comment',
            field=models.TextField(default='-'),
        ),
    ]
