# Generated by Django 2.1.5 on 2022-10-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_albumcomments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcomments',
            old_name='liked_album',
            new_name='commented_on_album',
        ),
        migrations.RenameField(
            model_name='albumcomments',
            old_name='liked_date',
            new_name='commented_on_date',
        ),
        migrations.RenameField(
            model_name='albumcomments',
            old_name='liked_user',
            new_name='commented_user',
        ),
    ]
