# Generated by Django 2.1.5 on 2022-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20221022_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomments',
            name='comment',
            field=models.TextField(default='-', max_length=500),
        ),
    ]
