# Generated by Django 2.1.5 on 2022-10-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0017_auto_20221022_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='-', max_length=500)),
                ('liked_date', models.DateTimeField()),
                ('liked_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Song Comments',
            },
        ),
        migrations.AlterModelOptions(
            name='albumcomments',
            options={'verbose_name_plural': 'Album Comments'},
        ),
    ]
