# Generated by Django 2.1.5 on 2022-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20221022_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
