# Generated by Django 2.1.5 on 2022-10-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_songcomments_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcomments',
            name='approved',
        ),
    ]
