# Generated by Django 2.1.5 on 2022-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_remove_albumcomments_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
