# Generated by Django 2.1.5 on 2022-10-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_songlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songlikes',
            old_name='iked_user',
            new_name='liked_user',
        ),
    ]
