# Generated by Django 2.1.5 on 2022-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20221025_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['alb_title'], 'verbose_name_plural': '   Albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['art_username'], 'verbose_name_plural': '    Artists'},
        ),
        migrations.AlterModelOptions(
            name='lyrics',
            options={'verbose_name_plural': ' Lyrics'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_title'], 'verbose_name_plural': '  Songs'},
        ),
        migrations.AlterModelOptions(
            name='songlikes',
            options={'verbose_name_plural': 'Song Likes'},
        ),
        migrations.AddField(
            model_name='albumcomments',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='alb_release_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='liked_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
