# Generated by Django 2.1.5 on 2022-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20221102_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomments',
            name='liked_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
