# Generated by Django 2.1.5 on 2022-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20221102_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomments',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
