# Generated by Django 2.1.5 on 2022-11-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
