# Generated by Django 2.1.5 on 2022-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_created_at', models.DateTimeField()),
                ('page_slug', models.CharField(max_length=100, unique=True)),
                ('page_title', models.CharField(max_length=100)),
                ('page_body', models.TextField()),
            ],
        ),
    ]
